<h1>About me</h1>
<p>
I graduated from the Miskatonic Institute of Technology where I majored in
computer science and minored in applied mythology. My thesis was
&ldquo;Zipf&apos;s law &amp; the Necronomicon&rdquo;.
</p>
<p>
I&apos;m now working on obscenity-tolerant data transmission protocols,
<abbr title="obscenity-tolerant data transmission protocols">OTDTP</abbr>,
at the Cosmodemonic Telegraph Company.
</p>

