name: macos-release

on:
  workflow_dispatch:

permissions: read-all

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-15-intel
          - macos-15

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout tree
        uses: actions/checkout@v6

      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5.4.0

      - name: Build soupault executable
        run: |
          opam install . --deps-only --with-test --yes
          opam exec -- dune build
          opam exec -- dune runtest

      - name: Build release tarball
        run: |
          export RELEASE_DIR=soupault-$(_build/default/src/soupault.exe --version | head -n 1 | cut -d ' ' -f 2)-macos-$(uname -m)
          mkdir $RELEASE_DIR
          cp _build/default/src/soupault.exe $RELEASE_DIR/soupault
          cp LICENSE $RELEASE_DIR/
          cp README.md $RELEASE_DIR/
          cp CHANGELOG.md $RELEASE_DIR/
          tar cvfz $RELEASE_DIR.tar.gz $RELEASE_DIR
          echo "RELEASE_TARBALL=$RELEASE_DIR.tar.gz" >> $GITHUB_ENV

      - name: Upload the release tarball
        uses: actions/upload-artifact@v7
        with:
          path: ${{env.RELEASE_TARBALL}}
          archive: false
          if-no-files-found: error
