name: windows-release

on:
  workflow_dispatch:

permissions: read-all

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-2025

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout tree
        uses: actions/checkout@v4

      - name: Set-up OCaml
        run: |
          winget install --disable-interactivity --accept-source-agreements --accept-package-agreements Git.Git OCaml.opam

      - name: Initialize the opam switch
        shell: pwsh
        run: |
          C:\Users\runneradmin\AppData\Local\Microsoft\WinGet\Links\opam.exe init --yes

      - name: Build soupault
        shell: pwsh
        run: |
          (& C:\Users\runneradmin\AppData\Local\Microsoft\WinGet\Links\opam.exe env) -split '\r?\n' | ForEach-Object { Invoke-Expression $_ }
          C:\Users\runneradmin\AppData\Local\Microsoft\WinGet\Links\opam.exe install . --deps-only --with-test
          dune build
          dune runtest

      - name: Upload the executable
        uses: actions/upload-artifact@v4
        with:
          name: soupault
          path: _build/default/src/soupault.exe
          if-no-files-found: error
