name: windows-release

on:
  workflow_dispatch:

permissions: read-all

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-2022

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout tree
        uses: actions/checkout@v6

      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5.4.0

      - name: Build soupault
        shell: pwsh
        run: |
          opam install . --deps-only --with-test --yes
          opam exec -- dune build
          opam exec -- dune runtest

      - name: Build release archive
        shell: pwsh
        run: |
          Set-Variable RELEASE_DIR soupault-$(./_build/default/src/soupault.exe --version | select -first 1 | ForEach-Object {([string]$_).Split(" ")[1]})-win64
          mkdir $RELEASE_DIR
          cp _build/default/src/soupault.exe $RELEASE_DIR/SOUPAULT.EXE
          # Modern Windows seems to be fine with Unix line ends
          # so we don't bother with conversion here
          cp LICENSE $RELEASE_DIR/LICENSE.TXT
          cp README.md $RELEASE_DIR/README.TXT
          cp CHANGELOG.md $RELEASE_DIR/CHANGELOG.TXT
          echo "RELEASE_DIR=$RELEASE_DIR" >> $GITHUB_ENV

      - name: Upload the release archive
        uses: actions/upload-artifact@v7
        with:
          path: soupault-*/*
          name: ${{env.RELEASE_DIR}}
          if-no-files-found: error
